spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/micropsilocol
    username: postgres
    password: Porras420
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    web:
      DEBUG